### ISSUE TITLE
Publish all secrets

### ISSUE THREAD

**Issue by cblgh** [ssb-ngi-pointer/ssb-fixtures#7]
I think this is something that @cryptix mentioned having requested before, but since I'm now in [ssb-server](https://github.com/ssbc/ssb-server) land with the [netsim](https://github.com/ssb-ngi-pointer/netsim) I figured I would make the request _official_ with an issue of its own.

I would like to request that ssb-fixtures, in some manner, provides all of the generated secrets for all authors in a corpus, instead of only one / a few (I think the data in one of the fixtures releases contain 3 for 500 authors).

This would help me create identities that can be controlled more closely by e.g. calling local-only muxrpc procedures.

Thanks for your hard work!

**Comment by staltz** [comment]
Good call!

Done, released as 2.3.0, and the 3 standard fixtures can be downloaded from here: https://github.com/ssb-ngi-pointer/ssb-fixtures/releases/tag/2.3.0

**Comment by cblgh** [comment]
Thanks!
