### ISSUE TITLE
Support index feeds

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-fixtures#8]
- CLI option to tell fixtures to generate index feeds for some main feeds
- The follow graph output should be mutated to replace a destination with its meta feed and index feeds

**Comment by arj03** [comment]
This is done, right? I have a small feature request. Can we have the number of messages written for each index on the output. Makes it easier to know how many messages we can expect.

**Comment by staltz** [comment]
You mean on the report.md right?

**Comment by staltz** [comment]
#12

**Comment by arj03** [comment]
Exactly :)
